name: CI with DVC and Azure

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      continue-on-error: false
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      continue-on-error: false
      with:
        python-version: 3.12

    # Step 3: Install dependencies
    - name: Install dependencies
      continue-on-error: false
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    # Step 4: Configure DVC with Azure
    - name: Configure DVC with Azure
      continue-on-error: false
      env:
        AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      run: |
        dvc version
        echo "Azure credentials set up."
        
        # Add remote for Azure storage        
        dvc remote modify azure_remote_mlps account_name $AZURE_STORAGE_ACCOUNT
        dvc remote modify azure_remote_mlps account_key $AZURE_STORAGE_KEY    

    # Step 5: Pull DVC data
    - name: Pull DVC data
      continue-on-error: false
      env:
        AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      run: |
        dvc pull
        ls -lh data/
        echo "DVC data pulled successfully."
